open("datosalquileres.pickle", "w").close()
open("datosbicicletas.pickle", "w").close()
open("datosclientes.pickle", "w").close()
open("datostrabajadores.pickle", "w").close()
open("datosestaciones.pickle", "w").close()