open("datos_alquileres.pickle", "w").close()
open("datos_bicicletas.pickle", "w").close()
open("datos_clientes.pickle", "w").close()
open("datos_trabajadores.pickle", "w").close()
open("datos_estaciones.pickle", "w").close()